name: Docker Pipeline

on:
  push:
    branches: [main]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      - uses: actions/checkout@v2
      - name: bun
        uses: oven-sh/setup-bun@v1
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login https://docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS
      - name: bun install
        run: |
          cd app && bun i
      - name: docker build
        run: |
          docker build . -t docker.pkg.github.com/josholaus/doofus-rick/web:latest
      - name: docker push
        run: |
          docker push docker.pkg.github.com/josholaus/doofus-rick/web:latest
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bun
        uses: oven-sh/setup-bun@v1
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          docker login https://docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASS
      - name: bun install
        run: |
          cd server && bun i
      - name: docker build
        run: |
          docker build . -t docker.pkg.github.com/josholaus/doofus-rick/bot:latest
      - name: docker push
        run: |
          docker push docker.pkg.github.com/josholaus/doofus-rick/bot:latest
